#! /bin/sh

echo "Sleeping for USB to apprear..."
sleep 10

case "$1" in
	start|"")
		echo "Starting wpa_supplicant..."
		/usr/sbin/wpa_supplicant -B -i wlan0 -D wext -c /etc/wpa_supplicant/home.conf
		;;
	stop)
		killall wpa_supplicant
		;;
	*)
		echo "Usage: wpa_supplicant {start|stop}" >&2
		exit 1
		;;
esac
