#! /bin/sh


case "$1" in
	start|"")
		/usr/sbin/wpa_supplicant -B -i wlan0 -D wext -c /etc/wpa_supplicant/home.conf
		;;
	stop)
		killall wpa_supplicant
		;;
	*)
		echo "Usage: wpa_supplicant {start|stop}" >&2
		exit 1
		;;
esac
