#! /bin/sh

err()
{
	echo "FAIL: $1"
	exit 1
}


FLEXWALL_HOSTNAME=flexwall_default
#TODO default static WAN IP config
FLEXWALL_WAN_MAC=de:ad:be:ef:ca:fe
FLEXWALL_LAN0_IP=10.10.10.254
FLEXWALL_LAN0_MASK=255.255.255.0
FLEXWALL_LAN0_NET=10.10.10.0/24
FLEXWALL_LAN0_MAC=00:00:de:ad:be:ef
DNSMASQ_DHCP_RANGE=10.10.10.1,10.10.10.200,72h
DNSMASQ_DHCP_ROUTER=$FLEXWALL_LAN0_IP
DNSMASQ_DHCP_NTP=$FLEXWALL_LAN0_IP

[ -e /mnt/flexwall.txt ] && source /mnt/flexwall.txt

NAME=GenerateConfig

case "$1" in
  start)
    echo -n "Starting $NAME: "

    mkdir /tmp/etc.rw || err "mkdir of etc.rw"
    mount -t unionfs -o dirs=/tmp/etc.rw=rw:/etc=ro unionfs /etc || err "unionfs mount of etc.rw"

    # DEBUG QEMU client
    if [ ! -z "$(grep fwclient /proc/cmdline)" ]; then
        echo "auto eth0"			>> /etc/network/interfaces
        echo "iface eth0 inet dhcp"	>> /etc/network/interfaces
        rm -f  /etc/nftables.ruleset   # disable firewall
        echo "Client: OK"
        exit 0
    fi

    echo .
    echo " HOSTNAME [$FLEXWALL_HOSTNAME]"
    echo " WAN MAC  [$FLEXWALL_WAN_MAC]"
    echo " LAN IP   [$FLEXWALL_LAN0_IP]"
    echo " LAN MSK  [$FLEXWALL_LAN0_MASK]"
    echo " LAN MAC  [$FLEXWALL_LAN0_MAC]"
    echo " LAN POOL [$DNSMASQ_DHCP_RANGE]"
    echo " LAN NTP  [$DNSMASQ_DHCP_NTP]"

    echo $FLEXWALL_HOSTNAME > /etc/hostname
    hostname -F /etc/hostname

    echo "auto eth0"				>> /etc/network/interfaces
    echo "iface eth0 inet dhcp"			>> /etc/network/interfaces
    echo "   hwaddress ether $FLEXWALL_WAN_MAC"	>> /etc/network/interfaces

    echo					 >> /etc/network/interfaces
    echo "auto eth1"				 >> /etc/network/interfaces
    echo "iface eth1 inet static"		 >> /etc/network/interfaces
    echo "   address $FLEXWALL_LAN0_IP"		 >> /etc/network/interfaces
    echo "   netmask $FLEXWALL_LAN0_MASK"	 >> /etc/network/interfaces
    echo "   hwaddress ether $FLEXWALL_LAN0_MAC" >> /etc/network/interfaces

    echo "dhcp-range=$DNSMASQ_DHCP_RANGE"		   >> /etc/dnsmasq.conf
    echo "dhcp-option=option:router,$DNSMASQ_DHCP_ROUTER"  >> /etc/dnsmasq.conf
    echo "dhcp-option=option:ntp-server,$DNSMASQ_DHCP_NTP" >> /etc/dnsmasq.conf

    sed -i "s~flexwall_lan_net~$FLEXWALL_LAN0_NET~g" /etc/nftables.ruleset

    echo "OK"
    ;;
  stop)
    echo  "Stopping $NAME: NA"
    ;;
  restart|reload)
    echo "Restarting $NAME: NA"
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|reload}" >&2
    exit 1
    ;;
esac

exit 0
