#! /bin/sh

NAME=sysctl
DAEMON=/sbin/$NAME

# Gracefully exit if the package has been removed.
test -x $DAEMON || exit 0

case "$1" in
  start)
    echo -n "Starting $NAME: "
    $DAEMON -p -q
    [ $? = 0 ] && echo "OK" || echo "FAIL"
    ;;
  stop)
    echo  "Stopping $NAME: NA"
    ;;
  restart|reload)
    echo "Restarting $NAME: "
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|reload}" >&2
    exit 1
    ;;
esac

exit 0
