#! /bin/sh

NAME=nft
DAEMON=/usr/sbin/$NAME

err()
{
	echo "$1"
	exit 1
}


# Gracefully exit if the package has been removed.
test -x $DAEMON || exit
[ ! -e /etc/nftables.ruleset ] && err "Missing Config"

case "$1" in
  start)
    echo -n "Starting $NAME: "
    $DAEMON -f /etc/nftables.ruleset
    [ $? = 0 ] && echo "OK" || echo "FAIL"
    ;;
  stop)
    echo "Stopping $NAME: NA"
    ;;
  restart|reload)
    echo "Restarting $NAME: "
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|reload}" >&2
    exit 1
    ;;
esac

exit 0
