#!/bin/sh
#
# Start the network....
#

# Debian ifupdown needs the /run/network lock directory
mkdir -p /run/network

case "$1" in
  start)
	printf "Starting network: "
	iptables-restore /etc/iptables.rules

	/sbin/ifup -a
	[ $? = 0 ] && echo "OK" || echo "FAIL"

#	CFG=/etc/ifplugd/ifplugd.conf
#	IFPLUGD=/usr/sbin/ifplugd
#	. $CFG
#	echo -n "Starting ifplugd: "
#	for IF in $INTERFACES ; do
#		A="`eval echo \$\{ARGS_${IF}\}`"
#		[ -z "$A" ] && A="$ARGS"
#		$IFPLUGD -i $IF $A
#		echo -n " $IF"
#	done

	;;
  stop)
	printf "Stopping network: "
	/sbin/ifdown -a
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

